# Generated by Django 3.2.8 on 2021-11-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_australia_india'),
    ]

    operations = [
        migrations.CreateModel(
            name='team1_batting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('balls', models.IntegerField()),
                ('runs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='team1_bowling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('overs', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='team2_batting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('balls', models.IntegerField()),
                ('runs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='team2_bowling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('overs', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
            ],
        ),
    ]
