# Generated by Django 3.2.8 on 2021-11-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_team1_batting_team1_bowling_team2_batting_team2_bowling'),
    ]

    operations = [
        migrations.AddField(
            model_name='team1_batting',
            name='bowler',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team1_batting',
            name='wicket',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team2_batting',
            name='bowler',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team2_batting',
            name='wicket',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
