# Generated by Django 3.2.8 on 2021-11-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20211115_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team1_bowling',
            name='overs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='team2_bowling',
            name='overs',
            field=models.FloatField(),
        ),
    ]
